// Renderer-backed alias-quality instrument and baseline (Plan B Task 2).
//
// Why the real renderer: for a multirate nonlinear stage the quality selector
// normally lives in the plug-in wrapper, so a DSP-core unit test cannot
// establish a *quality ordering*. See
// audio-knowledge/validation/renderer-quality-order-gate.md. This file measures
// folded-harmonic alias energy in audio that has passed through the actual
// HybridWavetableAudioProcessor, via the same OfflineRenderer the rest of the
// suite uses.
//
// The proxy: a single probe tone is played, and the metric compares the energy
// in a narrow band around the tone against the energy where the tone's third
// harmonic folds (|3*f0 - 48000| Hz). A linear path cannot put energy there, so
// whatever appears is generated by a nonlinearity and folded back by sampling.
// Relative to the tone, more-negative dB is cleaner.
//
// Why a band and not measureInharmonicAliasDbc: that metric marks +/-1.5 FFT
// bins around each expected harmonic as "legal", so it only works when the
// probe tone sits on an exact FFT bin. It cannot, here: every float parameter in
// this plug-in is quantised to a 0.01 step, because JUCE 8's
// AudioParameterFloat(id, name, min, max, default) constructor forwards to
// NormalisableRange(min, max, 0.01f). For osc1Tune (+/-24 semitones) that is a
// 1 cent grid, and 1 cent at 10 kHz is 5.8 Hz -- wider than the 2.93 Hz bin
// spacing of the 16384-point analysis. A tone that is 0.4 cents off leaks its
// Hann main lobe outside the legal bins and the metric reads -8.7 dBc of pure
// window leakage no matter how clean the audio is (measured during Task 2).
// Measuring a band 1.4 kHz away from any harmonic removes that dependence.
//
// What this file guarantees:
//   1. the renderer hits the requested pitch to better than 0.1 cent, and a
//      0.005 semitone tune change reaches the audio as 0.5 cent;
//   2. the renderer is deterministic (same seed and configuration, same samples);
//   3. the instrument measures what it claims: a line injected at the folded
//      frequency is reported within 1 dB from -40 down to -120 dBc, so the
//      ceiling gate below cannot pass vacuously; and
//   4. the saturation stage leaves no folded-harmonic energy above the ceiling
//      at either the default or the maximum drive.
//
// What it does NOT yet guarantee, and must not pretend to: the tier ordering
// Eco < Normal < High. The product has no saturation quality tier yet, so every
// tier label would render identically and such a gate would be meaningless.
// Task 3 adds the tier and the ordering assertion here, against this instrument.

// History worth keeping: this file originally proved its own sensitivity by
// driving the real saturation stage harder and requiring a 15 dB increase in
// folded energy. That worked while the stage was a naive tanh behind a JUCE IIR
// oversampler (-108.9 dBc at full drive). After Plan B Task 3 replaced it with
// antiderivative anti-aliasing plus a half-band FIR, both drive settings land on
// the render's own float32 noise floor (about -152 dBc) and the drive knob can
// no longer move the number. The gate was replaced by an injected-line
// calibration, which tests the instrument directly instead of relying on the
// product being dirty.

#include "../../Source/PluginProcessor.h"
#include "Metrics.h"
#include "OfflineRenderer.h"
#include "TestHarness.h"

#include <algorithm>
#include <array>
#include <cmath>
#include <cstdint>
#include <limits>
#include <vector>

namespace
{
constexpr double kSampleRate = 48000.0;
constexpr int kAnalysisSamples = 16384;
constexpr int kWarmupSamples = 4096;
constexpr int kMidiNote = 123;
constexpr std::uint32_t kSeed = 0x514f5244u;   // "QORD"
constexpr std::array<int, 3> kBlockSizes { 64, 127, 256 };

// Probe pitch. This is the nearest 0.01 semitone grid point to a 10 kHz probe,
// kept because the recorded baseline in docs/quality/b2-alias-baseline.md was
// measured here. The grid is no longer imposed by the plug-in (Plan B Task 2b
// made the float parameter ranges continuous), so a finer probe would work too;
// this value is now a deliberate choice rather than a constraint.
constexpr float kProbeTuneSemitones = 0.08f;

constexpr float kCleanSaturation = 0.15f;   // product default
constexpr float kHotSaturation = 1.0f;      // maximum drive

// Band half-widths. Both bands hold a single spectral line widened by the Hann
// window (about 12 Hz), so they only have to be wide enough to contain it. The
// alias band is kept narrow on purpose: the render is float32 and its
// quantisation noise is white, so every extra bin in the band raises the
// measurement floor without adding signal. Measured floor with a 150 Hz band is
// about -153 dBc; a 600 Hz band costs 6 dB for nothing.
constexpr double kToneBandHalfWidthHz = 300.0;
constexpr double kAliasBandHalfWidthHz = 150.0;

// The saturation stage must not leave folded-harmonic energy the instrument can
// still measure. The render's own float32 noise floor sits near -156 dBc on this
// proxy (measured with the non-linearity bypassed), so -150 dBc is the tightest
// ceiling this instrument can enforce with margin; anything below it is
// indistinguishable from the floor.
constexpr double kMaximumFoldedAliasDbc = -150.0;
constexpr double kMaximumPitchErrorCents = 0.1;

// Injection levels for the instrument calibration below.
constexpr std::array<double, 3> kCalibrationLevelsDbc { -40.0, -80.0, -120.0 };

double noteFrequencyHz()
{
    return 440.0 * std::exp2 ((kMidiNote - 69) / 12.0);
}

float probeTuneSemitones()
{
    return kProbeTuneSemitones;
}

double probeFrequencyHz()
{
    return noteFrequencyHz() * std::exp2 (probeTuneSemitones() / 12.0);
}

// Where the probe tone's third harmonic lands after folding at 48 kHz. This is
// the strongest fold for a symmetric-ish saturator, and it sits far from every
// legal harmonic of the probe.
double foldedThirdHarmonicHz()
{
    return std::abs (3.0 * probeFrequencyHz() - kSampleRate);
}

void configureAliasTone (HybridWavetableAudioProcessor& processor, float saturation,
                         float tuneSemitones)
{
    const auto set = [&processor] (const char* id, float value)
    {
        if (auto* parameter = processor.parameters.getParameter (id))
            parameter->setValueNotifyingHost (parameter->convertTo0to1 (value));
    };

    // Exactly one oscillator with one unison lane, on frame 0 of the default
    // table, which is a pure sine. Everything the probe picks up is therefore
    // generated downstream of the oscillator.
    set ("osc1Level", 1.0f);
    set ("osc2Level", 0.0f);
    set ("osc3Level", 0.0f);
    set ("osc1Pos", 0.0f);
    set ("osc1Unison", 1.0f);
    set ("osc1Tune", tuneSemitones);
    set ("unisonKeyTrack", 0.0f);

    // Static, unmodulated path. A moving cutoff or a decaying envelope would add
    // sidebands, and a band-based proxy cannot tell those apart from folds.
    set ("cutoff", 20000.0f);
    set ("resonance", 0.1f);
    set ("filterDrive", 0.0f);
    set ("filterType", 0.0f);
    set ("filterSlope", 1.0f);
    set ("filterEnvAmount", 0.0f);
    set ("ampAttack", 0.01f);
    set ("ampDecay", 0.01f);
    set ("ampSustain", 1.0f);
    set ("ampRelease", 0.01f);
    set ("filterAttack", 0.01f);
    set ("filterDecay", 0.01f);
    set ("filterSustain", 1.0f);
    set ("filterRelease", 0.01f);
    set ("lfo1Depth", 0.0f);
    set ("lfo2Depth", 0.0f);
    set ("driftDepth", 0.0f);
    set ("randomPhase", 0.0f);
    set ("arpEnabled", 0.0f);
    set ("delayMix", 0.0f);
    set ("reverbMix", 0.0f);
    set ("masterWidth", 1.0f);
    set ("output", 0.0f);
    set ("saturation", saturation);
}

juce::AudioBuffer<float> renderAliasTone (float saturation, int blockSize, std::uint32_t seed)
{
    audioquality::AudioQualityFixture fixture;
    fixture.id = "alias-probe-tone";
    fixture.sampleRate = kSampleRate;
    fixture.blockSize = blockSize;
    fixture.channels = 2;
    // Long enough that the analysis window always lies inside steady state.
    fixture.durationSeconds = 0.5;
    fixture.tailSeconds = 0.0;
    fixture.randomSeed = seed;
    fixture.midi = { { juce::MidiMessage::noteOn (1, kMidiNote, 0.8f), 0 } };

    return audioquality::OfflineRenderer::render (fixture, [saturation] (auto& processor)
    {
        configureAliasTone (processor, saturation, probeTuneSemitones());
    });
}

// Same probe, explicit tune: used by the parameter-resolution check below.
juce::AudioBuffer<float> renderAliasToneWithTune (float tuneSemitones)
{
    audioquality::AudioQualityFixture fixture;
    fixture.id = "alias-probe-resolution";
    fixture.sampleRate = kSampleRate;
    fixture.blockSize = kBlockSizes[1];
    fixture.channels = 2;
    fixture.durationSeconds = 0.5;
    fixture.tailSeconds = 0.0;
    fixture.randomSeed = kSeed;
    fixture.midi = { { juce::MidiMessage::noteOn (1, kMidiNote, 0.8f), 0 } };

    return audioquality::OfflineRenderer::render (fixture, [tuneSemitones] (auto& processor)
    {
        configureAliasTone (processor, kCleanSaturation, tuneSemitones);
    });
}

// Hann-windowed power sum over a frequency band, in dB, by direct DFT in
// double precision.
//
// Why not juce::dsp::FFT: it is float32, and its round-off floor sits around
// -150 dBc relative to a full-scale tone. After the saturation stage gained
// antiderivative anti-aliasing plus a half-band FIR, that floor *is* the
// measurement: the stage stopped producing folded energy the FFT could see, and
// the instrument could no longer tell the drive settings apart. A double
// direct DFT has no such floor here (the remaining limit is the float32
// quantisation of the rendered samples), so the instrument keeps its dynamic
// range after the thing it measures got better.
//
// Band selection is independent of the DFT grid, which is the point: the probe
// tone cannot be placed on an exact bin (see the file header).
double bandPowerDb (const float* samples, int count, double lowHz, double highHz)
{
    std::vector<double> windowed ((size_t) count);
    for (int i = 0; i < count; ++i)
    {
        const double phase = (double) i / (double) (count - 1);
        const double window = 0.5 * (1.0 - std::cos (2.0 * juce::MathConstants<double>::pi * phase));
        windowed[(size_t) i] = (double) samples[i] * window;
    }

    const double binWidth = kSampleRate / (double) count;
    const int firstBin = juce::jmax (1, (int) std::ceil (lowHz / binWidth));
    const int lastBin = (int) std::floor (highHz / binWidth);
    double power = 0.0;
    for (int bin = firstBin; bin <= lastBin; ++bin)
    {
        // sin/cos rotation recurrence instead of a trig call per sample: the
        // band holds hundreds of bins and the analysis window is 16384 long.
        const double omega = 2.0 * juce::MathConstants<double>::pi * (double) bin / (double) count;
        const double stepCos = std::cos (omega);
        const double stepSin = std::sin (omega);
        double re = 1.0, im = 0.0;
        double sumRe = 0.0, sumIm = 0.0;
        for (int i = 0; i < count; ++i)
        {
            const double x = windowed[(size_t) i];
            sumRe += x * re;
            sumIm += x * im;
            const double nextRe = re * stepCos - im * stepSin;
            im = re * stepSin + im * stepCos;
            re = nextRe;
        }
        power += sumRe * sumRe + sumIm * sumIm;
    }
    return 10.0 * std::log10 (std::max (power, 1.0e-30));
}

double foldedHarmonicAliasDbc (const juce::AudioBuffer<float>& buffer)
{
    const auto* samples = buffer.getReadPointer (0) + kWarmupSamples;
    const double tone = probeFrequencyHz();
    const double folded = foldedThirdHarmonicHz();
    const double toneBand = bandPowerDb (samples, kAnalysisSamples,
                                         tone - kToneBandHalfWidthHz, tone + kToneBandHalfWidthHz);
    const double aliasBand = bandPowerDb (samples, kAnalysisSamples,
                                          folded - kAliasBandHalfWidthHz, folded + kAliasBandHalfWidthHz);
    return aliasBand - toneBand;
}

// Independent pitch check that does not depend on the FFT grid at all:
// linearly interpolated positive-going zero crossings of a tone-dominated signal.
double measureFrequencyByZeroCrossings (const float* x, int count)
{
    double first = 0.0, last = 0.0;
    int crossings = 0;
    for (int i = 1; i < count; ++i)
    {
        if (x[i - 1] <= 0.0f && x[i] > 0.0f)
        {
            const double previous = (double) x[i - 1];
            const double current = (double) x[i];
            const double position = (double) (i - 1) + (0.0 - previous) / (current - previous);
            if (crossings == 0)
                first = position;
            last = position;
            ++crossings;
        }
    }
    if (crossings < 2)
        return 0.0;
    return (double) (crossings - 1) * kSampleRate / (last - first);
}

double medianOf (std::array<double, kBlockSizes.size()> values)
{
    std::sort (values.begin(), values.end());
    return values[values.size() / 2];
}

float maximumDifference (const juce::AudioBuffer<float>& a, const juce::AudioBuffer<float>& b)
{
    float result = 0.0f;
    const auto channels = juce::jmin (a.getNumChannels(), b.getNumChannels());
    const auto samples = juce::jmin (a.getNumSamples(), b.getNumSamples());
    for (int channel = 0; channel < channels; ++channel)
        for (int sample = 0; sample < samples; ++sample)
            result = juce::jmax (result, std::abs (a.getSample (channel, sample)
                                                   - b.getSample (channel, sample)));
    return result;
}

void runInstrumentTests (audioquality::TestHarness& test)
{
    const double expectedHz = probeFrequencyHz();
    const double foldedHz = foldedThirdHarmonicHz();

    std::printf ("Plan B alias-quality instrument\n");
    std::printf ("  note %d, probe tune %.3f semitones\n", kMidiNote, (double) probeTuneSemitones());
    std::printf ("  probe %.4f Hz, folded third harmonic %.4f Hz, analysis %d (double direct DFT), warm-up %d, seed 0x%08x\n",
                 expectedHz, foldedHz, kAnalysisSamples, kWarmupSamples, kSeed);

    // The measurement is only meaningful if the folded band cannot contain a
    // legal harmonic of the probe tone, and if it is inside the audio band.
    {
        const double secondHarmonic = 2.0 * expectedHz;
        const double aliasBandTop = foldedHz + kAliasBandHalfWidthHz;
        test.expect (foldedHz > 0.0 && aliasBandTop < kSampleRate * 0.5,
                     "the folded-harmonic band lies inside the audio band");
        test.expect (aliasBandTop < secondHarmonic - kToneBandHalfWidthHz,
                     "the folded-harmonic band cannot contain the probe's second harmonic");
        test.expect (foldedHz - kAliasBandHalfWidthHz
                         > expectedHz + kToneBandHalfWidthHz,
                     "the alias band and the tone band do not overlap");
    }

    // Pitch first: if the renderer does not land on the frequency the metric
    // assumes, every alias number below is measured in the wrong place.
    {
        const auto buffer = renderAliasTone (kCleanSaturation, kBlockSizes[1], kSeed);
        const double measured = measureFrequencyByZeroCrossings (buffer.getReadPointer (0) + kWarmupSamples,
                                                                kAnalysisSamples);
        const double cents = audioquality::centsError (measured, expectedHz);
        std::printf ("  pitch: expected %.4f Hz, measured %.4f Hz -> %+.4f cents\n",
                     expectedHz, measured, cents);
        test.expect (std::abs (cents) <= kMaximumPitchErrorCents,
                     "the renderer reaches the requested pitch within "
                         + juce::String (kMaximumPitchErrorCents, 1) + " cent");
    }

    // Determinism: every later number is worthless if a render is not
    // reproducible from the fixture seed.
    {
        const auto first = renderAliasTone (kHotSaturation, kBlockSizes[1], kSeed);
        const auto second = renderAliasTone (kHotSaturation, kBlockSizes[1], kSeed);
        test.expect (maximumDifference (first, second) == 0.0f,
                     "the renderer is deterministic for a fixed seed and configuration");
    }

    // Parameter resolution end to end. The probe pitch sits on the tune
    // parameter's old 0.01 semitone grid; before Task 2b, 0.070 and 0.075
    // snapped to the same value and rendered identically. A 0.5 cent move must
    // now reach the audio, otherwise the parameter is still misreporting its
    // resolution and this whole instrument is measuring a lie.
    {
        const auto coarse = renderAliasToneWithTune (0.07f);
        const auto fine = renderAliasToneWithTune (0.075f);
        const double coarseHz = measureFrequencyByZeroCrossings (coarse.getReadPointer (0)
                                                                    + kWarmupSamples, kAnalysisSamples);
        const double fineHz = measureFrequencyByZeroCrossings (fine.getReadPointer (0)
                                                                  + kWarmupSamples, kAnalysisSamples);
        const double cents = 1200.0 * std::log2 (fineHz / coarseHz);
        std::printf ("  resolution: tune 0.070 -> %.4f Hz, tune 0.075 -> %.4f Hz (%.4f cents apart)\n",
                     coarseHz, fineHz, cents);
        test.expect (std::abs (cents - 0.5) < 0.05,
                     "a 0.005 semitone tune change reaches the audio as 0.5 cent");
    }

    std::array<double, kBlockSizes.size()> cleanProxies {};
    std::array<double, kBlockSizes.size()> hotProxies {};

    for (size_t index = 0; index < kBlockSizes.size(); ++index)
    {
        const int blockSize = kBlockSizes[index];
        cleanProxies[index] = foldedHarmonicAliasDbc (renderAliasTone (kCleanSaturation, blockSize, kSeed));
        hotProxies[index] = foldedHarmonicAliasDbc (renderAliasTone (kHotSaturation, blockSize, kSeed));
        std::printf ("  block %3d  saturation %.2f -> %8.2f dBc   saturation %.2f -> %8.2f dBc\n",
                     blockSize, (double) kCleanSaturation, cleanProxies[index],
                     (double) kHotSaturation, hotProxies[index]);

        test.expect (std::isfinite (cleanProxies[index]) && std::isfinite (hotProxies[index]),
                     "alias proxy is finite at block size " + juce::String (blockSize));
    }

    const double cleanMedian = medianOf (cleanProxies);
    const double hotMedian = medianOf (hotProxies);
    std::printf ("  median: saturation %.2f -> %.2f dBc, saturation %.2f -> %.2f dBc, delta %.2f dB\n",
                 (double) kCleanSaturation, cleanMedian, (double) kHotSaturation, hotMedian,
                 hotMedian - cleanMedian);

    // Instrument floor, not a product gate: saturation 0 bypasses the nonlinear
    // stage entirely, so what remains is the measurement's own numerical floor
    // (mostly the float32 quantisation of the rendered samples). An improvement
    // can only be proven above this line.
    {
        const double floorProxy = foldedHarmonicAliasDbc (renderAliasTone (0.0f, kBlockSizes[1], kSeed));
        std::printf ("  instrument floor (saturation bypassed): %.2f dBc; clean path is %.2f dB above it, hot path %.2f dB\n",
                     floorProxy, cleanMedian - floorProxy, hotMedian - floorProxy);
    }

    // Instrument calibration. Inject a known line at the folded frequency into a
    // synthetic probe tone and require the proxy to report it. Without this, a
    // proxy that always returned -inf would pass the ceiling gate for free.
    {
        constexpr int total = kAnalysisSamples + kWarmupSamples;
        const double toneAmplitude = 0.5;
        for (const double injectedDbc : kCalibrationLevelsDbc)
        {
            const double lineAmplitude = toneAmplitude * std::pow (10.0, injectedDbc / 20.0);
            std::vector<float> injected ((size_t) total);
            for (int i = 0; i < total; ++i)
            {
                const double t = (double) i / kSampleRate;
                injected[(size_t) i] = (float) (toneAmplitude
                                                    * std::sin (2.0 * juce::MathConstants<double>::pi
                                                                * probeFrequencyHz() * t)
                                                + lineAmplitude
                                                      * std::sin (2.0 * juce::MathConstants<double>::pi
                                                                  * foldedThirdHarmonicHz() * t));
            }
            juce::AudioBuffer<float> synthetic (1, total);
            synthetic.copyFrom (0, 0, injected.data(), total);
            const double measured = foldedHarmonicAliasDbc (synthetic);
            std::printf ("  calibration: injected %.0f dBc -> measured %.2f dBc\n",
                         injectedDbc, measured);
            test.expect (std::abs (measured - injectedDbc) < 1.0,
                         "the folded-band proxy reports a " + juce::String (injectedDbc, 0)
                             + " dBc injected line within 1 dB");
        }
    }

    // Product gate: what the stage actually leaves behind. Both drive settings
    // must sit at or below the ceiling; the drive difference is reported above
    // but is not a gate, because after antiderivative anti-aliasing there is no
    // longer a meaningful amount of folded energy to scale with drive.
    test.expect (hotMedian <= kMaximumFoldedAliasDbc,
                 "folded-harmonic alias at maximum drive stays below "
                     + juce::String (kMaximumFoldedAliasDbc, 0) + " dBc");
    test.expect (cleanMedian <= kMaximumFoldedAliasDbc,
                 "folded-harmonic alias at the default drive stays below "
                     + juce::String (kMaximumFoldedAliasDbc, 0) + " dBc");
}
} // namespace

int main()
{
    audioquality::TestHarness test;
    runInstrumentTests (test);
    std::printf ("\n%d failure(s)\n", test.failureCount());
    return test.result();
}
