// Renderer-backed alias-quality instrument and baseline (Plan B Task 2).
//
// Why the real renderer: for a multirate nonlinear stage the quality selector
// normally lives in the plug-in wrapper, so a DSP-core unit test cannot
// establish a *quality ordering*. See
// audio-knowledge/validation/renderer-quality-order-gate.md. This file measures
// folded-harmonic alias energy in audio that has passed through the actual
// HybridWavetableAudioProcessor, via the same OfflineRenderer the rest of the
// suite uses.
//
// The proxy: a single probe tone is played, and the metric compares the energy
// in a narrow band around the tone against the energy where the tone's third
// harmonic folds (|3*f0 - 48000| Hz). A linear path cannot put energy there, so
// whatever appears is generated by a nonlinearity and folded back by sampling.
// Relative to the tone, more-negative dB is cleaner.
//
// Why a band and not measureInharmonicAliasDbc: that metric marks +/-1.5 FFT
// bins around each expected harmonic as "legal", so it only works when the
// probe tone sits on an exact FFT bin. It cannot, here: every float parameter in
// this plug-in is quantised to a 0.01 step, because JUCE 8's
// AudioParameterFloat(id, name, min, max, default) constructor forwards to
// NormalisableRange(min, max, 0.01f). For osc1Tune (+/-24 semitones) that is a
// 1 cent grid, and 1 cent at 10 kHz is 5.8 Hz -- wider than the 2.93 Hz bin
// spacing of the 16384-point analysis. A tone that is 0.4 cents off leaks its
// Hann main lobe outside the legal bins and the metric reads -8.7 dBc of pure
// window leakage no matter how clean the audio is (measured during Task 2).
// Measuring a band 1.4 kHz away from any harmonic removes that dependence.
//
// What this file guarantees today, while the product still has a single
// saturation quality path:
//   1. the renderer hits the requested pitch to better than 0.1 cent, on the
//      parameter's own quantisation grid;
//   2. the instrument is deterministic (same seed and configuration, same
//      samples); and
//   3. the instrument is sensitive: driving the real saturation stage harder
//      measurably increases folded-harmonic energy, so a later "quality tier X
//      is not worse than tier Y" gate cannot pass vacuously.
//
// What it does NOT yet guarantee, and must not pretend to: the tier ordering
// Eco < Normal < High. The product has no saturation quality tier yet, so every
// tier label would render identically and such a gate would be meaningless.
// Task 3 adds the tier and the ordering assertion here, against this instrument.

#include "../../Source/PluginProcessor.h"
#include "Metrics.h"
#include "OfflineRenderer.h"
#include "TestHarness.h"

#include <juce_dsp/juce_dsp.h>

#include <algorithm>
#include <array>
#include <cmath>
#include <cstdint>
#include <limits>
#include <vector>

namespace
{
constexpr double kSampleRate = 48000.0;
constexpr int kAnalysisSamples = 16384;
constexpr int kAnalysisOrder = 14;          // 16384-point FFT, matches kAnalysisSamples
constexpr int kWarmupSamples = 4096;
constexpr int kMidiNote = 123;
constexpr std::uint32_t kSeed = 0x514f5244u;   // "QORD"
constexpr std::array<int, 3> kBlockSizes { 64, 127, 256 };

// JUCE 8's AudioParameterFloat(id, name, min, max, default) forwards to
// NormalisableRange(min, max, 0.01f), so the tune parameter's grid is 0.01
// semitones (1 cent). Ask only for grid points, and compute the probe frequency
// from the value the renderer actually receives.
constexpr float kTuneGridSemitones = 0.01f;
constexpr double kTargetProbeHz = 10000.0;

constexpr float kCleanSaturation = 0.15f;   // product default
constexpr float kHotSaturation = 1.0f;      // maximum drive

// Band half-widths. The probe tone is a single spectral line, so the tone band
// only has to cover the line; the alias band is deliberately wide enough to
// catch the folded harmonic without reaching the second harmonic 1.4 kHz above.
constexpr double kToneBandHalfWidthHz = 300.0;
constexpr double kAliasBandHalfWidthHz = 600.0;

// Calibrated against the measured values recorded in
// docs/quality/b2-alias-baseline.md, with margin.
constexpr double kMinimumDriveSensitivityDb = 15.0;
constexpr double kMaximumPitchErrorCents = 0.1;

double noteFrequencyHz()
{
    return 440.0 * std::exp2 ((kMidiNote - 69) / 12.0);
}

float probeTuneSemitones()
{
    const double requested = 12.0 * std::log2 (kTargetProbeHz / noteFrequencyHz());
    return (float) (std::round (requested / kTuneGridSemitones) * kTuneGridSemitones);
}

double probeFrequencyHz()
{
    return noteFrequencyHz() * std::exp2 (probeTuneSemitones() / 12.0);
}

// Where the probe tone's third harmonic lands after folding at 48 kHz. This is
// the strongest fold for a symmetric-ish saturator, and it sits far from every
// legal harmonic of the probe.
double foldedThirdHarmonicHz()
{
    return std::abs (3.0 * probeFrequencyHz() - kSampleRate);
}

void configureAliasTone (HybridWavetableAudioProcessor& processor, float saturation)
{
    const auto set = [&processor] (const char* id, float value)
    {
        if (auto* parameter = processor.parameters.getParameter (id))
            parameter->setValueNotifyingHost (parameter->convertTo0to1 (value));
    };

    // Exactly one oscillator with one unison lane, on frame 0 of the default
    // table, which is a pure sine. Everything the probe picks up is therefore
    // generated downstream of the oscillator.
    set ("osc1Level", 1.0f);
    set ("osc2Level", 0.0f);
    set ("osc3Level", 0.0f);
    set ("osc1Pos", 0.0f);
    set ("osc1Unison", 1.0f);
    set ("osc1Tune", probeTuneSemitones());
    set ("unisonKeyTrack", 0.0f);

    // Static, unmodulated path. A moving cutoff or a decaying envelope would add
    // sidebands, and a band-based proxy cannot tell those apart from folds.
    set ("cutoff", 20000.0f);
    set ("resonance", 0.1f);
    set ("filterDrive", 0.0f);
    set ("filterType", 0.0f);
    set ("filterSlope", 1.0f);
    set ("filterEnvAmount", 0.0f);
    set ("ampAttack", 0.01f);
    set ("ampDecay", 0.01f);
    set ("ampSustain", 1.0f);
    set ("ampRelease", 0.01f);
    set ("filterAttack", 0.01f);
    set ("filterDecay", 0.01f);
    set ("filterSustain", 1.0f);
    set ("filterRelease", 0.01f);
    set ("lfo1Depth", 0.0f);
    set ("lfo2Depth", 0.0f);
    set ("driftDepth", 0.0f);
    set ("randomPhase", 0.0f);
    set ("arpEnabled", 0.0f);
    set ("delayMix", 0.0f);
    set ("reverbMix", 0.0f);
    set ("masterWidth", 1.0f);
    set ("output", 0.0f);
    set ("saturation", saturation);
}

juce::AudioBuffer<float> renderAliasTone (float saturation, int blockSize, std::uint32_t seed)
{
    audioquality::AudioQualityFixture fixture;
    fixture.id = "alias-probe-tone";
    fixture.sampleRate = kSampleRate;
    fixture.blockSize = blockSize;
    fixture.channels = 2;
    // Long enough that the analysis window always lies inside steady state.
    fixture.durationSeconds = 0.5;
    fixture.tailSeconds = 0.0;
    fixture.randomSeed = seed;
    fixture.midi = { { juce::MidiMessage::noteOn (1, kMidiNote, 0.8f), 0 } };

    return audioquality::OfflineRenderer::render (fixture, [saturation] (auto& processor)
    {
        configureAliasTone (processor, saturation);
    });
}

// Hann-windowed power sum over a frequency band, in dB. Band selection is
// independent of the FFT grid, which is the point: the probe tone cannot be
// placed on a bin.
double bandPowerDb (const float* samples, int count, double lowHz, double highHz)
{
    constexpr int fftSize = 1 << kAnalysisOrder;
    std::vector<float> data ((size_t) fftSize * 2u, 0.0f);
    const int used = juce::jmin (count, fftSize);
    for (int i = 0; i < used; ++i)
    {
        const double phase = (double) i / (double) (fftSize - 1);
        const double window = 0.5 * (1.0 - std::cos (2.0 * juce::MathConstants<double>::pi * phase));
        data[(size_t) i] = (float) ((double) samples[i] * window);
    }

    juce::dsp::FFT fft (kAnalysisOrder);
    fft.performRealOnlyForwardTransform (data.data());

    const double binWidth = kSampleRate / (double) fftSize;
    double power = 0.0;
    for (int bin = 1; bin < fftSize / 2; ++bin)
    {
        const double frequency = (double) bin * binWidth;
        if (frequency < lowHz || frequency > highHz)
            continue;
        const double re = (double) data[(size_t) 2 * (size_t) bin];
        const double im = (double) data[(size_t) 2 * (size_t) bin + 1];
        power += re * re + im * im;
    }
    return 10.0 * std::log10 (std::max (power, 1.0e-30));
}

double foldedHarmonicAliasDbc (const juce::AudioBuffer<float>& buffer)
{
    const auto* samples = buffer.getReadPointer (0) + kWarmupSamples;
    const double tone = probeFrequencyHz();
    const double folded = foldedThirdHarmonicHz();
    const double toneBand = bandPowerDb (samples, kAnalysisSamples,
                                         tone - kToneBandHalfWidthHz, tone + kToneBandHalfWidthHz);
    const double aliasBand = bandPowerDb (samples, kAnalysisSamples,
                                          folded - kAliasBandHalfWidthHz, folded + kAliasBandHalfWidthHz);
    return aliasBand - toneBand;
}

// Independent pitch check that does not depend on the FFT grid at all:
// linearly interpolated positive-going zero crossings of a tone-dominated signal.
double measureFrequencyByZeroCrossings (const float* x, int count)
{
    double first = 0.0, last = 0.0;
    int crossings = 0;
    for (int i = 1; i < count; ++i)
    {
        if (x[i - 1] <= 0.0f && x[i] > 0.0f)
        {
            const double previous = (double) x[i - 1];
            const double current = (double) x[i];
            const double position = (double) (i - 1) + (0.0 - previous) / (current - previous);
            if (crossings == 0)
                first = position;
            last = position;
            ++crossings;
        }
    }
    if (crossings < 2)
        return 0.0;
    return (double) (crossings - 1) * kSampleRate / (last - first);
}

double medianOf (std::array<double, kBlockSizes.size()> values)
{
    std::sort (values.begin(), values.end());
    return values[values.size() / 2];
}

float maximumDifference (const juce::AudioBuffer<float>& a, const juce::AudioBuffer<float>& b)
{
    float result = 0.0f;
    const auto channels = juce::jmin (a.getNumChannels(), b.getNumChannels());
    const auto samples = juce::jmin (a.getNumSamples(), b.getNumSamples());
    for (int channel = 0; channel < channels; ++channel)
        for (int sample = 0; sample < samples; ++sample)
            result = juce::jmax (result, std::abs (a.getSample (channel, sample)
                                                   - b.getSample (channel, sample)));
    return result;
}

void runInstrumentTests (audioquality::TestHarness& test)
{
    const double expectedHz = probeFrequencyHz();
    const double foldedHz = foldedThirdHarmonicHz();

    std::printf ("Plan B alias-quality instrument\n");
    std::printf ("  note %d, requested tune %.5f semitones, grid %.2f -> sent %.2f semitones\n",
                 kMidiNote, 12.0 * std::log2 (kTargetProbeHz / noteFrequencyHz()),
                 (double) kTuneGridSemitones, (double) probeTuneSemitones());
    std::printf ("  probe %.4f Hz, folded third harmonic %.4f Hz, FFT %d, warm-up %d, seed 0x%08x\n",
                 expectedHz, foldedHz, 1 << kAnalysisOrder, kWarmupSamples, kSeed);

    // The measurement is only meaningful if the folded band cannot contain a
    // legal harmonic of the probe tone, and if it is inside the audio band.
    {
        const double secondHarmonic = 2.0 * expectedHz;
        const double aliasBandTop = foldedHz + kAliasBandHalfWidthHz;
        test.expect (foldedHz > 0.0 && aliasBandTop < kSampleRate * 0.5,
                     "the folded-harmonic band lies inside the audio band");
        test.expect (aliasBandTop < secondHarmonic - kToneBandHalfWidthHz,
                     "the folded-harmonic band cannot contain the probe's second harmonic");
        test.expect (foldedHz - kAliasBandHalfWidthHz
                         > expectedHz + kToneBandHalfWidthHz,
                     "the alias band and the tone band do not overlap");
    }

    // Pitch first: if the renderer does not land on the frequency the metric
    // assumes, every alias number below is measured in the wrong place.
    {
        const auto buffer = renderAliasTone (kCleanSaturation, kBlockSizes[1], kSeed);
        const double measured = measureFrequencyByZeroCrossings (buffer.getReadPointer (0) + kWarmupSamples,
                                                                kAnalysisSamples);
        const double cents = audioquality::centsError (measured, expectedHz);
        std::printf ("  pitch: expected %.4f Hz, measured %.4f Hz -> %+.4f cents\n",
                     expectedHz, measured, cents);
        test.expect (std::abs (cents) <= kMaximumPitchErrorCents,
                     "the renderer reaches the requested pitch within "
                         + juce::String (kMaximumPitchErrorCents, 1) + " cent");
    }

    // Determinism: every later number is worthless if a render is not
    // reproducible from the fixture seed.
    {
        const auto first = renderAliasTone (kHotSaturation, kBlockSizes[1], kSeed);
        const auto second = renderAliasTone (kHotSaturation, kBlockSizes[1], kSeed);
        test.expect (maximumDifference (first, second) == 0.0f,
                     "the renderer is deterministic for a fixed seed and configuration");
    }

    std::array<double, kBlockSizes.size()> cleanProxies {};
    std::array<double, kBlockSizes.size()> hotProxies {};

    for (size_t index = 0; index < kBlockSizes.size(); ++index)
    {
        const int blockSize = kBlockSizes[index];
        cleanProxies[index] = foldedHarmonicAliasDbc (renderAliasTone (kCleanSaturation, blockSize, kSeed));
        hotProxies[index] = foldedHarmonicAliasDbc (renderAliasTone (kHotSaturation, blockSize, kSeed));
        std::printf ("  block %3d  saturation %.2f -> %8.2f dBc   saturation %.2f -> %8.2f dBc\n",
                     blockSize, (double) kCleanSaturation, cleanProxies[index],
                     (double) kHotSaturation, hotProxies[index]);

        test.expect (std::isfinite (cleanProxies[index]) && std::isfinite (hotProxies[index]),
                     "alias proxy is finite at block size " + juce::String (blockSize));
    }

    const double cleanMedian = medianOf (cleanProxies);
    const double hotMedian = medianOf (hotProxies);
    std::printf ("  median: saturation %.2f -> %.2f dBc, saturation %.2f -> %.2f dBc, delta %.2f dB\n",
                 (double) kCleanSaturation, cleanMedian, (double) kHotSaturation, hotMedian,
                 hotMedian - cleanMedian);

    // Instrument floor, not a product gate: saturation 0 bypasses the nonlinear
    // stage entirely, so what remains is the measurement's own numerical floor
    // (float32 FFT round-off and the render's own quantisation). Task 3 can only
    // prove an improvement that stays above this line at low drive.
    {
        const double floorProxy = foldedHarmonicAliasDbc (renderAliasTone (0.0f, kBlockSizes[1], kSeed));
        std::printf ("  instrument floor (saturation bypassed): %.2f dBc; clean path is %.2f dB above it, hot path %.2f dB\n",
                     floorProxy, cleanMedian - floorProxy, hotMedian - floorProxy);
    }

    // Sensitivity gate. If driving the real saturation stage harder does not move
    // the proxy, the instrument cannot judge any future quality tier.
    test.expect (hotMedian > cleanMedian + kMinimumDriveSensitivityDb,
                 "the alias proxy resolves harder saturation drive by at least "
                     + juce::String (kMinimumDriveSensitivityDb, 1) + " dB");
}
} // namespace

int main()
{
    audioquality::TestHarness test;
    runInstrumentTests (test);
    std::printf ("\n%d failure(s)\n", test.failureCount());
    return test.result();
}
